services:
  database:
    image: mysql:8.0.32
    container_name: my-mysql-container
    restart: always
    environment:
      MYSQL_DATABASE: 'bank'
      MYSQL_USER: 'bank_user'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - './volumes/mysql:/var/lib/mysql'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: my-phpmyadmin-container
    restart: always
    environment:
      PMA_HOST: database
      PMA_USER: bank_user
      PMA_PASSWORD: admin
    ports:
     - '8081:80'