package com.bank.bank.util;

public enum NomeAgencia {
    RIOBRANCO, MACEIO, MACAPA, MANAUS, SALVADOR, FORTALEZA, BRASILIA, VITORIA, GOIANIA, SAOLUIS, CUIABA, CAMPOGRANDE, BELOHORIZONTE, BELEM, JOAOPESSOA,
    CURITIBA, RECIFE, TERESINA, RIODEJANEIRO, NATAL, PORTOALEGRE, PORTOVELHO, BOAVISTA, FLORIANOPOLIS, SAOPAULO, ARACAJU, PALMAS
}
